---

- block:
    - name: deploy Jellyseerr
      include_tasks: install.yml
      when: ansible_local.jellyseerr_deployed is undefined

    - name: update Jellyseerr
      include_tasks: update.yml
      when: ansible_local.jellyseerr_deployed is defined
