---

- name: Filter Jellyseerr role
  block:
    - name: Deploy Jellyseerr
      ansible.builtin.include_tasks: install.yml
      when: ansible_local.jellyseerr_deployed is undefined

    - name: Update Jellyseerr
      ansible.builtin.include_tasks: update.yml
      when: ansible_local.jellyseerr_deployed is defined
