---

- block:
    - name: deploy Frigate
      include_tasks: install.yml
      when: ansible_local.frigate_deployed is undefined

    - name: update Frigate
      include_tasks: update.yml
      when: ansible_local.frigate_deployed is defined
