---

- name: Filter Frigate role
  block:
    - name: Deploy Frigate
      ansible.builtin.include_tasks: install.yml
      when: ansible_local.frigate_deployed is undefined

    - name: Update Frigate
      ansible.builtin.include_tasks: update.yml
      when: ansible_local.frigate_deployed is defined
