all:
  children:
    ####################
    nfs_share:
      hosts:

    ####################
    samba_share:
      hosts:

    ####################
    ftp_server:
      hosts:

    ####################
    ohmyzsh:
      hosts:
