---
- name: Add dependencies
  become: true
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - dirmngr
      - gnupg
      - ca-certificates

- name: Ensure group automedia exists
  become: true
  ansible.builtin.group:
    gid: 6789
    name: automedia
    state: present

- name: Add user automedia
  become: true
  ansible.builtin.user:
    name: automedia
    uid: 9876
    groups: automedia

- name: Add mono apt keys
  become: true
  ansible.builtin.apt_key:
    id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
    keyserver: hkp://keyserver.ubuntu.com:80
    state: present

- name: Add mono APT repository
  become: true
  ansible.builtin.apt_repository:
    # yamllint disable-line rule:line-length
    repo: "deb https://download.mono-project.com/repo/ubuntu stable-focal main"
    filename: mono-official-stable.list

- name: Install Mediaarea from deb package
  become: true
  ansible.builtin.apt:
    deb: https://mediaarea.net/repo/deb/repo-mediaarea_1.0-21_all.deb

- name: Add sonarr apt keys
  become: true
  ansible.builtin.apt_key:
    id: 2009837CBFFD68F45BC180471F4F90DE2A9B4BF8
    keyserver: hkp://keyserver.ubuntu.com:80
    state: present

- name: Add sonarr APT repository
  become: true
  ansible.builtin.apt_repository:
    # yamllint disable-line rule:line-length
    repo: "deb https://apt.sonarr.tv/ubuntu focal main"
    filename: sonarr

- name: Install sonarr
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: sonarr
    state: latest

- name: Change user and group in sonarr service
  become: true
  ansible.builtin.lineinfile:
    path: /etc/systemd/system/sonarr.service
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  loop:
    - {regexp: "^User=", line: "User=automedia"}
    - {regexp: "^Group=", line: "Group=automedia"}

- name: Change ownership of sonarr folders
  become: true
  ansible.builtin.file:
    path: /var/lib/sonarr
    owner: automedia
    group: automedia
    recurse: true

- name: Restart sonarr service
  become: true
  ansible.builtin.systemd:
    name: sonarr.service
    state: restarted

- name: Stamp as properly deployed
  ansible.builtin.include_role:
    name: helpers/tag_host
  vars:
    stamp: "sonarr_deployed"
