---
- name: Add dependencies
  become: true
  ansible.builtin.apt:
    name:
      - git
      - python3-pip
      - unzip

- name: Install python package dependencies
  become: true
  ansible.builtin.pip:
    name:
      - github3.py

- name: Create user/group promtail
  ansible.builtin.include_role:
    name: helpers/create_user_group
  vars:
    create_user_group_user_name: promtail
    create_user_group_group_name: promtail

- name: Get Promtail latest tag
  community.general.github_release:
    user: grafana
    repo: loki
    action: latest_release
  register: promtail_latest
  changed_when: false

- name: Grab promtail latest binaries
  become: true
  block:
    - name: Grab promtail's binaries
      ansible.builtin.unarchive:
        # yamllint disable-line rule:line-length
        src: https://github.com/grafana/loki/releases/download/{{ promtail_latest['tag'] }}/promtail-linux-amd64.zip
        dest: /opt
        owner: promtail
        group: promtail
        mode: a+x
        remote_src: true
    - name: Copy the promtail binaries under a proper name
      ansible.builtin.copy:
        remote_src: true
        src: /opt/promtail-linux-amd64
        dest: /opt/promtail
        owner: promtail
        group: promtail
        mode: a+x
    - name: Remove the long named promtail binaries
      ansible.builtin.file:
        path: /opt/promtail-linux-amd64
        state: absent


- name: Create the promtail config folder
  become: true
  ansible.builtin.file:
    dest: /etc/promtail
    owner: promtail
    group: promtail
    state: directory
    mode: 0755

- name: Add Promtail service
  become: true
  ansible.builtin.copy:
    src: promtail.service
    dest: /etc/systemd/system/promtail.service
    owner: root
    group: root
    mode: 0644

- name: Add Promtail config file
  become: true
  ansible.builtin.copy:
    src: >-
      {{
        inventory_dir + '/host_vars/'
        + inventory_hostname + '/files/promtail-config.yml'
      }}
    dest: /etc/promtail/config.yml
    owner: promtail
    group: promtail
    mode: 0755

- name: Enable and start Promtail service
  become: true
  ansible.builtin.systemd:
    name: promtail
    enabled: true
    state: started

- name: Stamp as properly deployed
  ansible.builtin.include_role:
    name: helpers/tag_host
  vars:
    tag_host_stamp: "promtail_deployed"
