---

- name: Filter Promtail role
  block:
    - name: Deploy Promtail
      ansible.builtin.include_tasks: install.yml
      when: ansible_local.promtail_deployed is undefined

    - name: Update Promtail
      ansible.builtin.include_tasks: update.yml
      when: ansible_local.promtail_deployed is defined
