---

- name: Filter Heimdall role
  block:

    - name: Deploy Heimdall
      ansible.builtin.include_tasks: install.yml
      when: ansible_local.heimdall_deployed is undefined

    - name: Update Heimdall
      ansible.builtin.include_tasks: update.yml
      when: ansible_local.heimdall_deployed is defined
