---
- name: Add dependencies
  become: true
  ansible.builtin.apt:
    name:
      - git
      - python3-pip

- name: Install python package dependencies
  become: true
  ansible.builtin.pip:
    name:
      - github3.py

- name: Create user/group prometheus
  ansible.builtin.include_role:
    name: helpers/create_user_group
  vars:
    create_user_group_user_name: prometheus
    create_user_group_group_name: prometheus

- name: Get Prometheus latest tag
  community.general.github_release:
    user: prometheus
    repo: prometheus
    token: "{{ github_token | default(omit) }}"
    action: latest_release
  register: prometheus_latest
  changed_when: false

- name: Create the prometheus opt folder
  become: true
  ansible.builtin.file:
    dest: /opt/prometheus
    owner: prometheus
    group: prometheus
    state: directory
    mode: 0755

- name: Grab prometheus latest binaries
  become: true
  ansible.builtin.unarchive:
    # yamllint disable-line rule:line-length
    src: https://github.com/prometheus/prometheus/releases/download/{{ prometheus_latest['tag'] }}/prometheus-{{ prometheus_latest['tag'] | regex_replace('^v', '') }}.linux-amd64.tar.gz
    dest: /opt/prometheus
    owner: prometheus
    group: prometheus
    mode: a+x
    remote_src: true
    extra_opts: [--strip-components=1]

- name: Create the prometheus config folder
  become: true
  ansible.builtin.file:
    dest: /etc/prometheus
    owner: prometheus
    group: prometheus
    state: directory
    mode: 0755

- name: Add Prometheus service
  become: true
  ansible.builtin.copy:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: 0644

- name: Add Prometheus config file
  become: true
  ansible.builtin.template:
    src: >-
      {{
        inventory_dir + '/host_vars/'
        + inventory_hostname + '/files/prometheus-config.yml'
      }}
    dest: /etc/prometheus/config.yml
    owner: prometheus
    group: prometheus
    mode: 0755

- name: Enable and start Prometheus service
  become: true
  ansible.builtin.systemd:
    name: prometheus
    enabled: true
    state: started

- name: Stamp as properly deployed
  ansible.builtin.include_role:
    name: helpers/tag_host
  vars:
    tag_host_stamp: "prometheus_deployed"
