---

- name: Get installed Prometheus version
  ansible.builtin.command: /opt/node_exporter/node_exporter --version
  register: result
  changed_when: false

- name: Get Node_Exporter latest tag
  community.general.github_release:
    user: prometheus
    repo: node_exporter
    token: "{{ github_token | default(omit) }}"
    action: latest_release
  register: node_exporter_latest
  changed_when: false

- name: Set installed Node_Exporter version
  ansible.builtin.set_fact:
    installed_node_exporter_version: "{{ result.stdout.split(' ')[2] }}"
    # yamllint disable-line rule:line-length
    latest_node_exporter_version: "{{ node_exporter_latest['tag'] | regex_replace('^v', '') }}"

- name: Add Node_Exporter service
  become: true
  ansible.builtin.copy:
    src: >-
      {{
        inventory_dir + '/host_vars/'
        + inventory_hostname + '/files/node_exporter.service'
      }}
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart_node_exporter

- name: Grab Node_exporter latest binaries
  become: true
  notify: restart_node_exporter
  when: latest_node_exporter_version != installed_node_exporter_version
  ansible.builtin.unarchive:
    # yamllint disable-line rule:line-length
    src: https://github.com/prometheus/node_exporter/releases/download/{{ node_exporter_latest['tag'] }}/node_exporter-{{ node_exporter_latest['tag'] | regex_replace('^v', '') }}.linux-amd64.tar.gz
    dest: /opt/node_exporter
    owner: prometheus
    group: prometheus
    mode: a+x
    remote_src: true
    extra_opts: [--strip-components=1]
