---
- name: Add Bookstack dependencies
  become: true
  ansible.builtin.apt:
    name:
      - git
      - unzip
      - apache2
      - php8.1
      - curl
      - composer
      - php8.1-fpm
      - php8.1-curl
      - php8.1-mbstring
      - php8.1-ldap
      - php8.1-tidy
      - php8.1-xml
      - php8.1-zip
      - php8.1-gd
      - php8.1-mysql
      - libapache2-mod-php8.1
      - default-mysql-server
      - python3-dev
      - default-libmysqlclient-dev
      - build-essential
      - python3-pip
    state: latest
    update_cache: true
    cache_valid_time: 1800

- name: Install mysqlclient python package
  become: true
  ansible.builtin.pip:
    name: mysqlclient

- name: Create mysql bookstack database
  become: true
  community.mysql.mysql_db:
    login_user: root
    name: bookstack
    state: present

- name: Create mysql user bookstack with bookstack database privileges
  block:
    - name: Load secret variables
      ansible.builtin.include_vars: >-
        {{
        inventory_dir + '/host_vars/' + inventory_hostname + '/.credentials.yml'
        }}

    - name: Create user
      become: true
      community.mysql.mysql_user:
        login_user: root
        name: bookstack
        password: "{{ bookstack_sql_password }}"
        priv: "bookstack.*:ALL"
        state: present

- name: Clone the bookstack webapp into /var/www
  become: true
  ansible.builtin.git:
    repo: https://github.com/BookStackApp/BookStack.git
    dest: /var/www/bookstack
    version: release
    umask: "022"

- name: Add Bookstack .env file
  block:
    - name: Load secret variables
      ansible.builtin.include_vars: >-
        {{
        inventory_dir + '/host_vars/' + inventory_hostname + '/.credentials.yml'
        }}

    - name: Add file
      become: true
      ansible.builtin.template:
        src: >-
          {{
          inventory_dir + '/host_vars/' + inventory_hostname + '/files/bookstack.env.j2'
          }}
        dest: /var/www/bookstack/.env
        owner: www-data
        group: www-data
        mode: 0755

- name: Install composer dependencies
  become: true
  ansible.builtin.shell: |
    export COMPOSER_ALLOW_SUPERUSER=1
    php /usr/bin/composer install --no-dev --no-plugins
  args:
    chdir: /var/www/bookstack/
  changed_when: false

- name: Run php artisan migrate
  become: true
  ansible.builtin.shell: |
    php artisan migrate --no-interaction --force
  args:
    chdir: /var/www/bookstack/
  changed_when: false

- name: Set Bookstack folder permission
  become: true
  ansible.builtin.file:
    dest: /var/www/bookstack
    owner: www-data
    group: www-data
    recurse: true

- name: Prepare Apache
  become: true
  ansible.builtin.command:
    cmd: "{{ item }}"
    chdir: /var/www/bookstack/
  with_items:
    - "a2enmod rewrite"
    - "a2enmod php8.1"
  changed_when: false

- name: Add Bookstack configuration file
  become: true
  ansible.builtin.copy:
    src: >-
      {{
      inventory_dir + '/host_vars/' + inventory_hostname + '/files/bookstack.apache.conf'
      }}
    dest: /etc/apache2/sites-available/bookstack.conf
    owner: www-data
    group: www-data
    mode: 0755

- name: Enable config and disable default site
  become: true
  ansible.builtin.command: "{{ item }}"
  with_items:
    - "/usr/sbin/a2ensite bookstack.conf"
    - "/usr/sbin/apachectl configtest"
    - "/usr/sbin/a2dissite 000-default.conf"
  changed_when: false

- name: Restart apache service
  become: true
  ansible.builtin.systemd:
    name: apache2
    enabled: true
    state: restarted

- name: Stamp as properly deployed
  ansible.builtin.include_role:
    name: helpers/tag_host
  vars:
    tag_host_stamp: "bookstack_deployed"
