---

- name: Filter Bookstack role
  block:
    - name: Deploy Bookstack
      ansible.builtin.include_tasks: install.yml
      when: ansible_local.bookstack_deployed is undefined

    - name: Update Bookstack
      ansible.builtin.include_tasks: update.yml
      when: ansible_local.bookstack_deployed is defined
