---
- block:
    - name: deploy Bookstack
      include_tasks: install.yml
      when: ansible_local.bookstack_deployed is undefined

    - name: update Bookstack
      include_tasks: update.yml
      when: ansible_local.bookstack_deployed is defined
