---
- name: Install Grafana dependencies
  become: true
  ansible.builtin.apt:
    name:
      - curl
      - gnupg
    state: latest

- name: Add Grafana GPG key
  become: true
  ansible.builtin.get_url:
    url: "https://apt.grafana.com/gpg.key"
    dest: /etc/apt/trusted.gpg.d/grafana.key
    owner: root
    group: root
    mode: 0644

- name: Add Grafana APT sources
  become: true
  ansible.builtin.apt_repository:
    repo: >-
      deb [signed-by=/etc/apt/trusted.gpg.d/grafana.key]
       https://apt.grafana.com stable main
    filename: grafana
    state: present

- name: Install Grafana
  become: true
  ansible.builtin.apt:
    name: grafana-enterprise
    update_cache: true
    state: latest

- name: Change Grafana's provisioning folder
  become: true
  ansible.builtin.lineinfile:
    path: /etc/grafana/grafana.ini
    regexp: "^;provisioning"
    line: "provisioning = /etc/grafana/provisioning"
    state: present

- name: Add Grafana's Provisioning
  become: true
  ansible.builtin.copy:
    src: >-
      {{
        inventory_dir + '/host_vars/' + inventory_hostname + '/files/provisioning/'
      }}
    dest: /etc/grafana/provisioning
    mode: 0644
    owner: root
    group: grafana

- name: Add Grafana's Dashboards
  become: true
  ansible.builtin.copy:
    src: >-
      {{
        inventory_dir + '/host_vars/' + inventory_hostname + '/files/dashboards/'
      }}
    dest: /var/lib/grafana/dashboards
    mode: 0755
    owner: grafana
    group: grafana


- name: Start and Enable Grafana service
  become: true
  ansible.builtin.systemd:
    name: grafana-server
    enabled: true
    state: started

- name: Stamp as properly deployed
  ansible.builtin.include_role:
    name: helpers/tag_host
  vars:
    stamp: "grafana_deployed"
