---
- name: Install Grafana dependencies
  become: true
  ansible.builtin.apt:
    name:
      - curl
      - gnupg
    state: latest

- name: Add Grafana GPG key
  become: true
  ansible.builtin.get_url:
    url: "https://apt.grafana.com/gpg.key"
    dest: /etc/apt/trusted.gpg.d/grafana.key
    owner: root
    group: root
    mode: 0644

- name: Add Grafana APT sources
  become: true
  ansible.builtin.apt_repository:
    repo: >-
      deb [signed-by=/etc/apt/trusted.gpg.d/grafana.key]
       https://apt.grafana.com stable main
    filename: grafana
    state: present

- name: Install Grafana
  become: true
  ansible.builtin.apt:
    name: grafana-enterprise
    update_cache: true
    state: latest

- name: Change Grafana's provisioning folder
  become: true
  ansible.builtin.lineinfile:
    path: /etc/grafana/grafana.ini
    regexp: "^;provisioning"
    line: "provisioning = /etc/grafana/provisioning"
    state: present

- name: Create the Grafana's provisioning folders
  become: true
  ansible.builtin.file:
    path: "{{ '/etc/grafana/provisioning/' + item }}"
    owner: grafana
    group: grafana
    state: directory
    mode: 0755
  with_items:
    - ""
    - "access-control"
    - "alerting"
    - "dashboards"
    - "datasources"
    - "notifiers"
    - "plugins"

- name: Add Grafana's Provisioning
  block:
    - name: Load secret variables
      ansible.builtin.include_vars: >-
        {{
         inventory_dir + '/host_vars/' + inventory_hostname + '/.credentials.yml'
        }}

    - name: Add Grafana's Provisioning
      become: true
      vars:
        provisioning_folder: >-
          {{
            inventory_dir + '/host_vars/' + inventory_hostname + '/files/provisioning/'
          }}
      ansible.builtin.template:
        src: "{{ item }}"
        dest: >-
          {{
            '/etc/grafana/provisioning/'
            + item | dirname | regex_replace('.*/','')
            + '/'
            + item | basename | regex_replace('\.j2$', '')
          }}
        mode: 0644
        owner: root
        group: grafana
      with_fileglob:
        - "{{ provisioning_folder + 'access-control/*.j2' }}"
        - "{{ provisioning_folder + 'alerting/*.j2' }}"
        - "{{ provisioning_folder + 'dashboards/*.j2' }}"
        - "{{ provisioning_folder + 'datasources/*.j2' }}"
        - "{{ provisioning_folder + 'notifiers/*.j2' }}"
        - "{{ provisioning_folder + 'plugins/*.j2' }}"

- name: Start and Enable Grafana service
  become: true
  ansible.builtin.systemd:
    name: grafana-server
    enabled: true
    state: started

- name: Stamp as properly deployed
  ansible.builtin.include_role:
    name: helpers/tag_host
  vars:
    tag_host_stamp: "grafana_deployed"
