---

- name: Filter Grafana role
  block:
    - name: Deploy Grafana
      ansible.builtin.include_tasks: install.yml
      when: ansible_local.grafana_deployed is undefined

    - name: Update Grafana
      ansible.builtin.include_tasks: update.yml
      when: ansible_local.grafana_deployed is defined
