---
- block:
    - name: deploy Grafana
      include_tasks: install.yml
      when: ansible_local.grafana_deployed is undefined

    - name: update Grafana
      include_tasks: update.yml
      when: ansible_local.grafana_deployed is defined
