---

- name: Copy the Lodestar beacon service file over
  become: true
  ansible.builtin.copy:
    src: >-
      {{
        inventory_dir + '/host_vars/' + inventory_hostname + '/files/beacon.service'
      }}
    dest: '/etc/systemd/system/lodestar-beacon.service'
    owner: root
    group: root
    mode: 0644

- name: Start and enable Lodestar Beacon
  become: true
  ansible.builtin.systemd:
    name: lodestar-beacon
    enabled: true
    state: started

- name: Stamp as properly deployed
  ansible.builtin.include_role:
    name: helpers/tag_host
  vars:
    tag_host_stamp: "lodestar_beacon_deployed"
