---

- name: Filter lodestar beacon role
  block:

    - name: Deploy lodestar beacon
      ansible.builtin.include_tasks: install.yml
      when: ansible_local.lodestar_beacon_deployed is undefined

    - name: Update lodestar beacon
      ansible.builtin.include_tasks: update.yml
      when: ansible_local.lodestar_beacon_deployed is defined
