---

- name: Create group cryptobro
  become: true
  ansible.builtin.group:
    name: cryptobro
    gid: 1337
    state: present

- name: Create user cryptobro
  become: true
  ansible.builtin.user:
    name: cryptobro
    uid: 1337
    state: present
    groups: cryptobro

- name: Create variable folders
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    owner: cryptobro
    group: cryptobro
    mode: 0755
    state: directory
  loop:
    - /var/lib/avalanchego
    - /var/lib/avalanchego/configs
    - /var/lib/avalanchego/chain-data

- name: Add avalanchego GPG key
  become: true
  ansible.builtin.get_url:
    url: "https://downloads.avax.network/avalanchego.gpg.key"
    dest: /etc/apt/trusted.gpg.d/avalanchego.asc
    owner: root
    group: root
    mode: 0644

- name: Add AvalancheGo APT sources
  become: true
  ansible.builtin.apt_repository:
    repo: "deb https://downloads.avax.network/apt {{ ansible_distribution_release }} main"
    filename: avalanchego
    state: present

- name: Add AvalancheGo
  become: true
  ansible.builtin.apt:
    name: avalanchego
    state: latest
    update_cache: true

- name: Copy the Avalanche files over
  become: true
  ansible.builtin.copy:
    src: "{{ item.source }}"
    dest: "{{ item.dest }}"
    owner: cryptobro
    group: cryptobro
    mode: 0644
  loop:
    - {
      source: "{{
        inventory_dir + '/host_vars/' + inventory_hostname + '/files/node.json'
        }}",
      dest: '/var/lib/avalanchego/configs/node.json'
    }
    - {
      source: 'avalanchego.service',
      dest: '/etc/systemd/system/avalanchego.service'
    }

- name: Start and enable AvalancheGo
  become: true
  ansible.builtin.systemd:
    name: avalanchego
    enabled: true
    state: started

- name: Stamp as properly deployed
  ansible.builtin.include_role:
    name: helpers/tag_host
  vars:
    stamp: "avalanchego_deployed"
