---

- name: Filter avalanchego role
  block:

    - name: Deploy avalanchego
      ansible.builtin.include_tasks: install.yml
      when: ansible_local.avalanchego_deployed is undefined

    - name: Update avalanchego
      ansible.builtin.include_tasks: update.yml
      when: ansible_local.avalanchego_deployed is defined
