---

- name: Filter sabnzbd role
  block:

    - name: Deploy sabnzbd
      ansible.builtin.include_tasks: install.yml
      when: ansible_local.sabnzbd_deployed is undefined

    - name: Update sabnzbd
      ansible.builtin.include_tasks: update.yml
      when: ansible_local.sabnzbd_deployed is defined
