---

- block:
    - name: deploy NFS share
      include_tasks: install.yml
      when: ansible_local.nfs_deployed is undefined

    - name: update NFS share
      include_tasks: update.yml
      when: ansible_local.nfs_deployed is defined
