---

- name: Install Nzbget package and dependencies
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
    cache_valid_time: 1800
  loop:
    - unrar
    - nzbget

- name: Ensure group automedia exists
  become: true
  ansible.builtin.group:
    gid: 6789
    name: automedia
    state: present

- name: Add user automedia
  become: true
  ansible.builtin.user:
    name: automedia
    uid: 9876
    groups: automedia

- name: Copy the service file on the remote
  become: true
  ansible.builtin.copy:
    src: nzbget.service
    dest: /etc/systemd/system/nzbget.service
    owner: root
    group: root
    mode: 0644

- name: Create the nzbget config folder
  become: true
  ansible.builtin.file:
    dest: /etc/nzbget
    owner: automedia
    group: automedia
    state: directory
    mode: 0755

- name: Copy nzbget configuration on the remote
  block:
    - name: Load secret variables
      ansible.builtin.include_vars: >-
        {{
         inventory_dir + '/host_vars/' + inventory_hostname + '/.credentials.yml'
        }}

    - name: Copy file
      become: true
      ansible.builtin.template:
        src: >-
          {{
           inventory_dir + '/host_vars/' + inventory_hostname + '/files/nzbget.conf.j2'
          }}
        dest: /etc/nzbget/nzbget.conf
        owner: automedia
        group: automedia
        mode: 0755

- name: Start/Restart nzbget service
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: nzbget
    enabled: true
    state: restarted

- name: Stamp as properly deployed
  ansible.builtin.include_role:
    name: helpers/tag_host
  vars:
    tag_host_stamp: "nzbget_deployed"
