---

- block:
    - name: deploy nzbget
      include_tasks: install.yml
      when: ansible_local.nzbget_deployed is undefined

    - name: update nzbget
      include_tasks: update.yml
      when: ansible_local.nzbget_deployed is defined
