---

- name: Filter Nzbget role
  block:
    - name: Deploy nzbget
      ansible.builtin.include_tasks: install.yml
      when: ansible_local.nzbget_deployed is undefined

    - name: Update nzbget
      ansible.builtin.include_tasks: update.yml
      when: ansible_local.nzbget_deployed is defined
