---

- name: Create group {{ create_user_group_group_name }}
  become: true
  ansible.builtin.group:
    name: "{{ create_user_group_group_name }}"
    gid: "{{ create_user_group_gid | default(omit) }}"
    state: present

- name: Create user {{ create_user_group_user_name }}
  become: true
  ansible.builtin.user:
    name: "{{ create_user_group_user_name }}"
    uid: "{{ create_user_group_uid | default(omit) }}"
    state: present
    groups: "{{ create_user_group_group_name }}"
