---

- name: Filter Gitea role
  block:
    - name: Deploy Gitea
      ansible.builtin.include_tasks: install.yml
      when: ansible_local.gitea_deployed is undefined

    - name: Update Gitea
      ansible.builtin.include_tasks: update.yml
      when: ansible_local.gitea_deployed is defined

    - name: Deploy Gitea Actions
      ansible.builtin.include_tasks: actions_install.yml
      when: gitea_actions is true and ansible_local.gitea_actions_deployed is undefined

    - name: Update Gitea Actions
      ansible.builtin.include_tasks: actions_update.yml
      when: gitea_actions is true and ansible_local.gitea_actions_deployed is defined
