---

- name: Filter Gitea role
  block:
    - name: Deploy Gitea
      ansible.builtin.include_tasks: install.yml
      when: ansible_local.gitea_deployed is undefined

    - name: Update Gitea
      ansible.builtin.include_tasks: update.yml
      when: ansible_local.gitea_deployed is defined
