---

- block:
    - name: deploy Gitea
      include_tasks: install.yml
      when: ansible_local.gitea_deployed is undefined

    - name: update Gitea
      include_tasks: update.yml
      when: ansible_local.gitea_deployed is defined
