---

- name: Add emqx Repository and Dependencies
  become: true
  ansible.builtin.script: install.sh
  register: installstdout
  failed_when: "'The repository is setup' not in installstdout.stdout"

- name: Install Emqx
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: emqx
    state: latest

- name: Add Emqx configuration file
  become: true
  ansible.builtin.copy:
    src: >-
      {{
      inventory_dir + '/host_vars/' + inventory_hostname + '/files/emqx.conf'
      }}
    dest: /etc/emqx/emqx.conf
    owner: emqx
    group: emqx
    mode: 0644

- name: Start and Enable emqx service
  become: true
  ansible.builtin.systemd:
    name: emqx
    enabled: true
    state: restarted

- name: Stamp as properly deployed
  ansible.builtin.include_role:
    name: helpers/tag_host
  vars:
    stamp: "emqx_deployed"
