---

- name: Install emqx dependencies
  become: true
  ansible.builtin.apt:
    name:
      - curl
      - gnupg
    update_cache: true
    cache_valid_time: 1800

- name: Add emqx GPG key
  become: true
  ansible.builtin.get_url:
    url: "https://packages.emqx.com/emqx/emqx/gpgkey"
    dest: /etc/apt/trusted.gpg.d/emqx.asc
    owner: root
    group: root
    mode: 0644

- name: Add emqx APT sources
  become: true
  ansible.builtin.template:
    src: emqx.sources.j2
    dest: /etc/apt/sources.list.d/emqx.sources
    owner: root
    group: root
    mode: 0644

- name: Install Emqx
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: emqx
    state: latest

- name: Add Emqx configuration file
  become: true
  ansible.builtin.copy:
    src: >-
      {{
      inventory_dir + '/host_vars/' + inventory_hostname + '/files/emqx.conf'
      }}
    dest: /etc/emqx/emqx.conf
    owner: emqx
    group: emqx
    mode: 0644

- name: Start and Enable emqx service
  become: true
  ansible.builtin.systemd:
    name: emqx
    enabled: true
    state: started

- name: Stamp as properly deployed
  ansible.builtin.include_role:
    name: helpers/tag_host
  vars:
    stamp: "emqx_deployed"
