---
- block:
    - name: deploy EMQX
      include_tasks: install.yml
      when: ansible_local.emqx_deployed is undefined

    - name: update EMQX
      include_tasks: update.yml
      when: ansible_local.emqx_deployed is defined
