---

- name: Filter EMQX role
  block:
    - name: Deploy EMQX
      ansible.builtin.include_tasks: install.yml
      when: ansible_local.emqx_deployed is undefined

    - name: Update EMQX
      ansible.builtin.include_tasks: update.yml
      when: ansible_local.emqx_deployed is defined
