---

- name: Install Geth dependencies
  become: true
  ansible.builtin.apt:
    name:
      - python3-pip
      - git
    state: latest
    update_cache: true
    cache_valid_time: 1800

- name: Install python package dependencies
  become: true
  ansible.builtin.pip:
    name:
      - github3.py

- name: Install golang for geth
  ansible.builtin.include_role:
    name: helpers/install_golang

- name: Create user/group cryptobro
  ansible.builtin.include_role:
    name: helpers/create_user_group
  vars:
    create_user_group_user_name: cryptobro
    create_user_group_uid: 1337
    create_user_group_group_name: cryptobro
    create_user_group_gid: 1337

- name: Create geth folders
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    owner: cryptobro
    group: cryptobro
    mode: 0755
    state: directory
  loop:
    - /var/opt/geth
    - /var/opt/geth/chain-data

- name: Clone and set Geth repo permission
  block:
    - name: Clone geth git repo
      become: true
      ansible.builtin.git:
        repo: "{{ geth_custom_git_url }}"
        version: "{{ geth_custom_git_branch | default('master') }}"
        dest: /opt/geth

    - name: Build Geth
      become: true
      community.general.make:
        chdir: /opt/geth
        target: geth
      environment:
        PATH: /sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/usr/local/go/bin

    - name: Set Geth folder permission
      become: true
      ansible.builtin.file:
        dest: /opt/geth
        owner: cryptobro
        group: cryptobro
        recurse: true

- name: Copy the Geth config file over
  become: true
  ansible.builtin.copy:
    src: >-
      {{
        inventory_dir + '/host_vars/' + inventory_hostname + '/files/config.toml'
      }}
    dest: "/var/opt/geth/config.toml"
    owner: cryptobro
    group: cryptobro
    mode: 0644

- name: Copy the geth service file over
  become: true
  ansible.builtin.copy:
    src: >-
      {{
        inventory_dir + '/host_vars/' + inventory_hostname + '/files/geth.service'
      }}
    dest: /etc/systemd/system/geth.service
    owner: root
    group: root
    mode: 0644

- name: Add Geth jwt file
  block:
    - name: Load secret variables
      ansible.builtin.include_vars: >-
        {{
         inventory_dir + '/host_vars/' + inventory_hostname + '/.credentials.yml'
        }}

    - name: Create the jwt file
      become: true
      ansible.builtin.copy:
        content: "{{ geth_jwt_secret }}"
        dest: /var/opt/geth/jwt.hex
        owner: cryptobro
        group: cryptobro
        mode: 0644
      when: geth_jwt_secret is defined

    - name: Add jwt line to geth service
      become: true
      ansible.builtin.lineinfile:
        path: /etc/systemd/system/geth.service
        line: "          --authrpc.jwtsecret=/var/opt/geth/jwt.hex \\"
        insertafter: "^ExecStart"
      when: geth_jwt_secret is defined

- name: Change /var/lib to /var/opt for git installed Geth
  become: true
  ansible.builtin.replace:
    path: /etc/systemd/system/geth.service
    replace: "{{ item.replace }}"
    regexp: "{{ item.regexp }}"
  loop:
    - {
      regexp: "--datadir /var/lib/",
      replace: "--datadir /var/opt/"
    }
    - {
      regexp: "--config /var/lib/",
      replace: "--config /var/opt/"
    }
    - {
      regexp: "/usr/bin/geth",
      replace: "/opt/geth/build/bin/geth"
    }

- name: Start and enable Geth
  become: true
  ansible.builtin.systemd:
    name: geth
    enabled: true
    state: started

- name: Stamp as properly deployed
  ansible.builtin.include_role:
    name: helpers/tag_host
  vars:
    tag_host_stamp: "geth_deployed"
