---

- name: Install Geth dependencies
  become: true
  ansible.builtin.apt:
    name:
      - gnupg
    state: latest
    update_cache: true
    cache_valid_time: 1800

- name: Create user/group cryptobro
  ansible.builtin.include_role:
    name: helpers/create_user_group
  vars:
    create_user_group_user_name: cryptobro
    create_user_group_uid: 1337
    create_user_group_group_name: cryptobro
    create_user_group_gid: 1337

- name: Create variable folders
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    owner: cryptobro
    group: cryptobro
    mode: 0755
    state: directory
  loop:
    - /var/lib/geth
    - /var/lib/geth/chain-data

- name: Add Ethereum PPA repository
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:ethereum/ethereum

- name: Install ethereum package
  become: true
  ansible.builtin.apt:
    name: ethereum
    state: latest
    update_cache: true

- name: Copy the Geth config file over
  become: true
  ansible.builtin.copy:
    src: >-
      {{
        inventory_dir + '/host_vars/' + inventory_hostname + '/files/config.toml'
      }}
    dest: "/var/lib/geth/config.toml"
    owner: cryptobro
    group: cryptobro
    mode: 0644

- name: Copy the geth service file over
  become: true
  ansible.builtin.copy:
    src: >-
      {{
        inventory_dir + '/host_vars/' + inventory_hostname + '/files/geth.service'
      }}
    dest: /etc/systemd/system/geth.service
    owner: root
    group: root
    mode: 0644

- name: Add Geth jwt file
  block:
    - name: Load secret variables
      ansible.builtin.include_vars: >-
        {{
         inventory_dir + '/host_vars/' + inventory_hostname + '/.credentials.yml'
        }}

    - name: Create the jwt file
      become: true
      ansible.builtin.copy:
        content: "{{ geth_jwt_secret }}"
        dest: /var/lib/geth/jwt.hex
        owner: cryptobro
        group: cryptobro
        mode: 0644
      when: geth_jwt_secret is defined

    - name: Add jwt line to geth service
      become: true
      ansible.builtin.lineinfile:
        path: /etc/systemd/system/geth.service
        line: "          --authrpc.jwtsecret=/var/lib/geth/jwt.hex \\"
        insertafter: "^ExecStart"
      when: geth_jwt_secret is defined

- name: Start and enable Geth
  become: true
  ansible.builtin.systemd:
    name: geth
    enabled: true
    state: started

- name: Stamp as properly deployed
  ansible.builtin.include_role:
    name: helpers/tag_host
  vars:
    tag_host_stamp: "geth_deployed"
