---

- name: Filter geth role
  block:

    - name: Deploy geth
      ansible.builtin.include_tasks: install.yml
      when: ansible_local.geth_deployed is undefined

    - name: Update geth
      ansible.builtin.include_tasks: update.yml
      when: ansible_local.geth_deployed is defined
