---

- name: Update Geth
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
    cache_valid_time: 1800
  loop:
    - ethereum
    - geth
  notify: Restart geth service

- name: Copy the Geth config file over
  become: true
  ansible.builtin.copy:
    src: >-
      {{
        inventory_dir + '/host_vars/' + inventory_hostname + '/files/config.toml'
      }}
    dest: /var/lib/geth/config.toml
    owner: cryptobro
    group: cryptobro
    mode: 0644
  notify: Restart geth service

- name: Copy the geth service file over
  become: true
  ansible.builtin.copy:
    src: >-
      {{
        inventory_dir + '/host_vars/' + inventory_hostname + '/files/geth.service'
      }}
    dest: /etc/systemd/system/geth.service
    owner: root
    group: root
    mode: 0644
  notify: Restart geth service
