---
- name: Add dependencies
  become: true
  ansible.builtin.apt:
    name:
      - git
      - python3-pip
      - unzip

- name: Install python package dependencies
  become: true
  ansible.builtin.pip:
    name:
      - github3.py

- name: Create user/group loki
  ansible.builtin.include_role:
    name: helpers/create_user_group
  vars:
    create_user_group_user_name: loki
    create_user_group_group_name: loki

- name: Get Loki latest tag
  community.general.github_release:
    user: grafana
    repo: loki
    token: "{{ github_token | default(omit) }}"
    action: latest_release
  register: loki_latest
  changed_when: false

- name: Grab loki latest binaries
  become: true
  block:
    - name: Grab loki's binaries
      ansible.builtin.unarchive:
        # yamllint disable-line rule:line-length
        src: https://github.com/grafana/loki/releases/download/{{ loki_latest['tag'] }}/loki-linux-amd64.zip
        dest: /opt
        owner: loki
        group: loki
        mode: a+x
        remote_src: true
    - name: Copy the loki binaries under a proper name
      ansible.builtin.copy:
        remote_src: true
        src: /opt/loki-linux-amd64
        dest: /opt/loki
        owner: loki
        group: loki
        mode: a+x
    - name: Remove the long named loki binaries
      ansible.builtin.file:
        path: /opt/loki-linux-amd64
        state: absent

- name: Create the loki config folder
  become: true
  ansible.builtin.file:
    dest: /etc/loki
    owner: loki
    group: loki
    state: directory
    mode: 0755

- name: Add Loki service
  become: true
  ansible.builtin.copy:
    src: loki.service
    dest: /etc/systemd/system/loki.service
    owner: root
    group: root
    mode: 0644

- name: Add Loki config file
  block:
    - name: Load secret variables
      ansible.builtin.include_vars: >-
        {{
         inventory_dir + '/host_vars/' + inventory_hostname + '/.credentials.yml'
        }}

    - name: Add Loki config file
      become: true
      ansible.builtin.template:
        src: >-
          {{
           inventory_dir + '/host_vars/'
           + inventory_hostname + '/files/loki-config.yml.j2'
          }}
        dest: /etc/loki/config.yml
        owner: loki
        group: loki
        mode: 0755

- name: Enable and start Loki service
  become: true
  ansible.builtin.systemd:
    name: loki
    enabled: true
    state: started

- name: Stamp as properly deployed
  ansible.builtin.include_role:
    name: helpers/tag_host
  vars:
    tag_host_stamp: "loki_deployed"
