---

- name: Filter FTP server role
  block:

    - name: Deploy FTP server
      ansible.builtin.include_tasks: install.yml
      when: ansible_local.ftp_deployed is undefined

    - name: Update FTP server
      ansible.builtin.include_tasks: update.yml
      when: ansible_local.ftp_deployed is defined
