---

- name: Filter Homepage role
  block:
    - name: Deploy Homepage
      ansible.builtin.include_tasks: install.yml
      when: ansible_local.homepage_deployed is undefined

    - name: Update Homepage
      ansible.builtin.include_tasks: update.yml
      when: ansible_local.homepage_deployed is defined
