---

- name: Filter Paperless-ngx role
  block:
    - name: Deploy paperless-ngx
      ansible.builtin.include_tasks: install.yml
      when: ansible_local.paperless_deployed is undefined

    - name: Update paperless-ngx
      ansible.builtin.include_tasks: update.yml
      when: ansible_local.paperless_deployed is defined
