---

- block:
    - name: deploy paperless-ngx
      include_tasks: install.yml
      when: ansible_local.paperless_deployed is undefined

    - name: update paperless-ngx
      include_tasks: update.yml
      when: ansible_local.paperless_deployed is defined
