---

- name: Copy docker-compose template
  block:
    - name: Load secret variables
      ansible.builtin.include_vars: >-
        {{
         inventory_dir + '/host_vars/' + inventory_hostname + '/.credentials.yml'
        }}

    - name: Copy docker-compose.yml
      become: true
      ansible.builtin.template:
        src: >-
          {{
           inventory_dir + '/host_vars/' + inventory_hostname +
           '/files/paperless-ngx.docker-compose.yml.j2'
          }}
        dest: /opt/paperless/docker-compose.yml
        owner: root
        group: root
        mode: 0644
      notify: Restart docker service

    - name: Copy docker-compose.env
      become: true
      ansible.builtin.template:
        src: >-
          {{
           inventory_dir + '/host_vars/' + inventory_hostname +
           '/files/paperless-ngx.docker-compose.env.j2'
          }}
        dest: /opt/paperless/docker-compose.env
        owner: root
        group: root
        mode: 0644
      notify: Restart docker service

- name: "Update docker service image"
  become: true
  ansible.builtin.command:
    chdir: /opt/paperless
    cmd: "docker compose pull"
  changed_when: true
  notify: Start updated paperless docker service
