---

- name: Filter Samba share role
  block:

    - name: Deploy Samba share
      ansible.builtin.include_tasks: install.yml
      when: ansible_local.samba_deployed is undefined

    - name: Update Samba share
      ansible.builtin.include_tasks: update.yml
      when: ansible_local.samba_deployed is defined
