---
- block:
    - name: deploy Jellyfin
      include_tasks: install.yml
      when: ansible_local.jellyfin_deployed is undefined

    - name: update Jellyfin
      include_tasks: update.yml
      when: ansible_local.jellyfin_deployed is defined