---

- name: Filter Jellyfin role
  block:
    - name: Deploy Jellyfin
      ansible.builtin.include_tasks: install.yml
      when: ansible_local.jellyfin_deployed is undefined

    - name: Update Jellyfin
      ansible.builtin.include_tasks: update.yml
      when: ansible_local.jellyfin_deployed is defined
