---

- name: Deploy Mailcow
  include_tasks: install.yml
  when: ansible_local.mailcow_deployed is undefined

- name: Update Mailcow
  include_tasks: update.yml
  when: ansible_local.mailcow_deployed is defined
