---

- name: Filter Mailcow role
  block:
    - name: Deploy Mailcow
      ansible.builtin.include_tasks: install.yml
      when: ansible_local.mailcow_deployed is undefined

    - name: Update Mailcow
      ansible.builtin.include_tasks: update.yml
      when: ansible_local.mailcow_deployed is defined
