---

- name: Filter nethermind role
  block:

    - name: Deploy nethermind
      ansible.builtin.include_tasks: install.yml
      when: ansible_local.nethermind_deployed is undefined

    - name: Update nethermind
      ansible.builtin.include_tasks: update.yml
      when: ansible_local.nethermind_deployed is defined
