---

- name: Restart Cloudbreaver Docker
  become: true
  community.docker.docker_container:
    name: cloudbeaver
    image: dbeaver/cloudbeaver
    state: started
    restart: true
    comparisons:
      "*": ignore
