---

- name: Filter lodestar base role
  block:

    - name: Deploy lodestar base infrastructure
      ansible.builtin.include_tasks: install.yml
      when: ansible_local.lodestar_base_deployed is undefined

    - name: Update lodestar base infrastructure
      ansible.builtin.include_tasks: update.yml
      when: ansible_local.lodestar_base_deployed is defined
