---

- name: Filter geth role
  block:

    - name: Deploy lodestar validator
      ansible.builtin.include_tasks: install.yml
      when: ansible_local.lodestar_validator_deployed is undefined

    - name: Update lodestar validator
      ansible.builtin.include_tasks: update.yml
      when: ansible_local.lodestar_validator_deployed is defined
