---

- name: Change the password for the provided user
  hosts: all
  vars_prompt:
    - name: username
      prompt: What is your username?
      private: false

    - name: password
      prompt: What is your new password?

  tasks:
    - name: Change user password for all defined hosts
      become: true
      ansible.builtin.user:
        user: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"
