---

- name: Create a Node folder template
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create node if node name is provided
      when: node_name is defined
      block:
        - name: Create node folder
          ansible.builtin.file:
            mode: 0744
            path: "{{ base_dir }}/proxmox_nodes/{{ node_name }}"
            state: directory
            recurse: true

        - name: Create host var folders
          ansible.builtin.copy:
            src: "{{ base_dir }}/global_files/node_template.yml"
            dest: "{{ base_dir }}/proxmox_nodes/{{ node_name }}/main.yml"
            force: false
            mode: 0744

        - name: Create host .token file  # noqa args[module]
          ansible.builtin.copy:
            content: >-
              {{ 'node_token: CHANGEME' | ansible.builtin.vault(vault_secret) }}"
            dest: "{{ base_dir }}/proxmox_nodes/{{ node_name }}/.token"
            decrypt: false
            mode: 0744

    - name: Node name is undefined
      ansible.builtin.fail:
        msg: >-
          you need to set the node name with -e "node_name=<node_name>"
          to generate the folder
      when: node_name is undefined
  vars:
    vault_secret: "{{ lookup('password', '../.vault_key') }}"
    base_dir: "{{ (ansible_inventory_sources[0] | dirname) }}"
