---

server:
    http_listen_port: 9080
    grpc_listen_port: 0

positions:
    filename: /tmp/positions.yaml

clients:
    - url: http://ip_or_hostname_where_loki_runs:3100/loki/api/v1/push

scrape_configs:
    - job_name: journal
      journal:
          max_age: 12h
          labels:
              job: systemd-journal
      relabel_configs:
          - source_labels: ['__journal__systemd_unit']
            target_label: 'unit'
    - job_name: syslog
      syslog:
          listen_address: 0.0.0.0:1514
          labels:
              job: "syslog"
      relabel_configs:
          - source_labels: ['__syslog_message_hostname']
            target_label: 'host'
    - job_name: push1
      loki_push_api:
          server:
              http_listen_port: 3500
              grpc_listen_port: 3600
          labels:
              pushserver: push1
