---

- name: Filter Bor role
  block:

    - name: Deploy Bor
      ansible.builtin.include_tasks: install.yml
      when: ansible_local.bor_deployed is undefined

    - name: Update Bor
      ansible.builtin.include_tasks: update.yml
      when: ansible_local.bor_deployed is defined
