---

- block:
    - name: deploy CloudBeaver
      include_tasks: install.yml
      when: ansible_local.cloudbeaver_deployed is undefined

    - name: update CloudBeaver
      include_tasks: update.yml
      when: ansible_local.cloudbeaver_deployed is defined
