---

- name: Filter Cloudbeaver role
  block:
    - name: Deploy CloudBeaver
      ansible.builtin.include_tasks: install.yml
      when: ansible_local.cloudbeaver_deployed is undefined

    - name: Update CloudBeaver
      ansible.builtin.include_tasks: update.yml
      when: ansible_local.cloudbeaver_deployed is defined
