---

- name: Filter xmrig role
  block:
    - name: Deploy xmrig
      ansible.builtin.include_tasks: install.yml
      when: ansible_local.xmrig_deployed is undefined

    - name: Update xmrig
      ansible.builtin.include_tasks: update.yml
      when: ansible_local.xmrig_deployed is defined
